# Generated by Django 2.2.4 on 2019-08-26 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=15)),
                ('equipamiento', models.TextField(max_length=200)),
                ('imagen', models.ImageField(upload_to='')),
            ],
        ),
    ]
