# Generated by Django 2.2.5 on 2019-10-02 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('box', '0002_mensaje'),
    ]

    operations = [
        migrations.AddField(
            model_name='box',
            name='proposito',
            field=models.TextField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='box',
            name='equipamiento',
            field=models.TextField(max_length=170),
        ),
        migrations.AlterField(
            model_name='mensaje',
            name='correo',
            field=models.EmailField(max_length=50),
        ),
    ]
