# Generated by Django 2.2.5 on 2019-10-02 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('box', '0003_auto_20191002_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='box',
            name='proposito',
            field=models.TextField(default='', max_length=150),
        ),
    ]
